### ISSUE TITLE
Can't Upload a Track Changed Docx File When used 18.3.0.47.jar on java

### ISSUE THREAD

**Issue by wesleyJia** [SyncfusionExamples/EJ2-DocumentEditor-WebServices#7]
1. Copy syncfusion-ej2-wordprocessor-18.3.0.47.jar, syncfusion-docio-18.3.0.47.jar, syncfusion-javahelper-18.3.0.47.jar from build installed locaion
2. Run this Java Demo
3. Call the /api/wordeditor/Import API, Throw Error
java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Lcon.syncfusion.docio.Revison;]]

**Comment by wesleyJia** [comment]
java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Lcom.syncfusion.docio.Revision;
	at com.syncfusion.docio.WordDocument.paragraphItemRevision(WordDocument.java:7328)
	at com.syncfusion.docio.DocxParser.checkTrackChange(DocxParser.java:36147)
	at com.syncfusion.docio.DocxParser.parseRunValues(DocxParser.java:11748)
	at com.syncfusion.docio.DocxParser.parseRun(DocxParser.java:11773)
	at com.syncfusion.docio.DocxParser.parseParagraphItems(DocxParser.java:7093)
	at com.syncfusion.docio.DocxParser.updateInsDelRevision(DocxParser.java:36227)
	at com.syncfusion.docio.DocxParser.parseParagraphItems(DocxParser.java:7145)
	at com.syncfusion.docio.DocxParser.parseBody(DocxParser.java:6700)
	at com.syncfusion.docio.DocxParser.parseDocument(DocxParser.java:6455)
	at com.syncfusion.docio.DocxParser.parseDocument(DocxParser.java:1483)
	at com.syncfusion.docio.DocxParser.read(DocxParser.java:1209)
	at com.syncfusion.docio.DocxParser.read(DocxParser.java:1153)
	at com.syncfusion.docio.WordDocument.openDocx(WordDocument.java:3577)
	at com.syncfusion.docio.WordDocument.openInternal(WordDocument.java:4308)
	at com.syncfusion.docio.WordDocument.open_Internal(WordDocument.java:4255)
	at com.syncfusion.docio.WordDocument.<init>(WordDocument.java:2950)
	at com.syncfusion.docio.WordDocument.<init>(WordDocument.java:2946)

**Comment by wesleyJia** [comment]
the doc file on importing
[Uploading Getting Started Track Change.docx…]()

**Comment by wesleyJia** [comment]
The doc file on importing
[Getting Started Track Change.docx](https://github.com/SyncfusionExamples/EJ2-DocumentEditor-WebServices/files/5702550/Getting.Started.Track.Change.docx)

**Comment by gunasekarant** [comment]
Hi @wesleyJia,

We are glad to announce that our Essential Studio 2021 Volume 2 release v19.2.0.44 is rolled out and is available for download under the following link.
[Essential Studio 2021 Volume 2 Main Release v19.2.0.44 is available for download | Announcements Forums | Syncfusion](https://www.syncfusion.com/forums/166800/essential-studio-2021-volume-2-main-release-v19-2-0-44-is-available-for-download)

In this release, we have included support for track changes in Java library. 

Kindly upgrade the latest version to resolve this reported issue. Please refer the below documentation for more information about downloading syncfusion-ej2-wordprocessor JAR file.
https://ej2.syncfusion.com/documentation/document-editor/web-services/java/#download-jar-file

Please let us know if you need any further assistance.

Regards
Gunasekaran
